stages:
    - test

test-code:
    stage: test
    tags:
        - g51csf_2021_exercise_1_assessor
    artifacts:
        name: "$CI_COMMIT_REF_NAME"
        when: on_success
        expire_in: 1 week
        paths:
            - log/
    script:
        - run_test

